parameters:
    nginx_push_stream.connection.class: Alawar\NginxPushStreamBundle\Connection\Connection
    nginx_push_stream.filter.hash.class: Alawar\NginxPushStreamBundle\Filter\Hash
    nginx_push_stream.filter.prefix.class: Alawar\NginxPushStreamBundle\Filter\Prefix

services:
    nginx_push_stream.connection_prototype:
        class: %nginx_push_stream.connection.class%
        abstract: true
        #arguments: [@service_id, %parameter%]