parameters:
#    nginx_push_stream.example.class: Alawar\NginxPushStreamBundle\Example

services:
#    nginx_push_stream.example:
#        class: %nginx_push_stream.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
